[package]
name = "cf-systems-assignment"
version = "0.1.0"
authors = ["Raymond Tran <raytran@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
